-- ============================================================
-- 2026-08-26 记忆关系边（V1 检索层）
-- 在 Supabase SQL Editor 手动执行（不自动迁移）。幂等，可重跑。
-- 规范说明见 sql/memory_relations.sql。
-- ============================================================

CREATE TABLE IF NOT EXISTS memory_relations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_topic TEXT NOT NULL,
  target_topic TEXT NOT NULL,
  rel_type TEXT NOT NULL
    CHECK (rel_type IN ('触发','导致','贡献','改善','解释','更新','同类')),
  note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_topic, target_topic, rel_type)
);

CREATE INDEX IF NOT EXISTS idx_memory_relations_source ON memory_relations (source_topic);
CREATE INDEX IF NOT EXISTS idx_memory_relations_target ON memory_relations (target_topic);

-- 2026-09-09 停用：这些迁移是幂等设计、随时可能被重跑，重跑一次就会把 RLS 关回去。
-- 后端用的是 secret key（绕过 RLS），前端不直连 Supabase，所以根本不需要关 RLS。
-- 原语句保留在下方注释里备查，不再执行。
-- ALTER TABLE memory_relations DISABLE ROW LEVEL SECURITY;
