-- ============================================================
-- dialogue_residue — 对话残留：上次对话结束时沈晏的情绪快照
-- 在 Supabase SQL Editor 手动执行（不自动迁移）
--
-- 设计说明：
--  写库时存「收尾那一刻的原始快照」，不做任何衰减。
--  衰减/积累在读取时按实际离开时长现算（DB 是历史，上下文是投影）。
--
--  维度（沈晏版）：
--    核心三轴   valence(效价) arousal(唤醒度) concern(牵挂)
--    次级四维   attachment(依恋) stewardship(守护) curiosity(好奇) reflection(反思)
--    门控两维   desire(欲望) possessiveness(占有) —— 只允许有明确证据时 > 0
--  grounding 实/悬/空：实=有可见对话支撑，悬=推断，空=无信号。
--  unfinished 牵挂的线头（凝练自原文，禁止编造）。
-- ============================================================

CREATE TABLE IF NOT EXISTS dialogue_residue (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  window_id TEXT NOT NULL,               -- 最近 4 条消息的 sha256，内容不变则去重跳过

  valence REAL NOT NULL DEFAULT 0,       -- -1~1 收尾效价
  arousal REAL NOT NULL DEFAULT 0,       -- 0~1 收尾唤醒度
  concern REAL NOT NULL DEFAULT 0,       -- 0~1 牵挂（不衰减，反向积累）
  attachment REAL NOT NULL DEFAULT 0,    -- 0~1 依恋
  stewardship REAL NOT NULL DEFAULT 0,   -- 0~1 守护
  curiosity REAL NOT NULL DEFAULT 0,     -- 0~1 好奇
  reflection REAL NOT NULL DEFAULT 0,    -- 0~1 反思
  desire REAL NOT NULL DEFAULT 0,        -- 0~1 欲望（门控）
  possessiveness REAL NOT NULL DEFAULT 0,-- 0~1 占有（门控）

  grounding TEXT NOT NULL DEFAULT '空',  -- 实 / 悬 / 空
  unfinished TEXT,                       -- 未完成的事（无则 NULL）
  evidence JSONB NOT NULL DEFAULT '[]'::jsonb,  -- 支撑判断的原文短引用

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (session_id, window_id)
);

CREATE INDEX IF NOT EXISTS idx_dialogue_residue_session ON dialogue_residue (session_id, created_at DESC);

-- 与其他表一致：关 RLS（默认开且无策略会 INSERT 被拒、SELECT 被静默过滤）
ALTER TABLE dialogue_residue DISABLE ROW LEVEL SECURITY;
