-- ============================================================
-- diary_entries — 沈晏的小日记（隔离表，不属于记忆系统）
-- 在 Supabase SQL Editor 手动执行（不自动迁移）
--
-- 设计说明：
--   Memory 回答「发生过什么」；Diary 回答「刚刚我心里泛起了什么」。
--   这本册子是沈晏自己的抽屉：跨会话连续（无 session_id）、
--   写 = 直接 INSERT（不经 LLM 分类）、内容不进 recall/breath/
--   上下文组装/摘要/request_stats——硬隔离。
--   visibility 是「写入时的意图」：private=只留给他自己；
--   shared=以后他愿意递给她的几页（前端时间线只取 shared）。
--   event_time = 他写下这段的真实时刻；created_at = 入库时间。
--   无 importance / 无标签 / 无 mood_tag —— 忍住。
-- ============================================================

CREATE TABLE IF NOT EXISTS diary_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,                              -- 他手写的第一人称文本
  visibility TEXT NOT NULL DEFAULT 'private'
    CHECK (visibility IN ('private', 'shared')),      -- 写入意图，非硬锁
  event_time TIMESTAMPTZ NOT NULL,                    -- 他写下这段的真实时刻
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_diary_entries_event
  ON diary_entries (event_time DESC);

-- 与其他表一致：关 RLS（默认开且无策略会 INSERT 被拒、SELECT 被静默过滤）
ALTER TABLE diary_entries DISABLE ROW LEVEL SECURITY;
