-- ============================================================
-- memory_topics — 记忆主题索引：服务端"编辑者"的差分写回底座
-- 在 Supabase SQL Editor 手动执行（不自动迁移）
--
-- 设计说明：
--   messages 表是历史（永久保留，演化永远在逐字记录里）。
--   Ombre 桶是当前投影（不重复建桶、无变化不动、变化只动该处）。
--   memory_topics 记录「每个主题 → Ombre 桶 → 上次写入内容」，
--   让差分写回（零变化跳过 / trace 手术更新）不需要每次重搜 Ombre。
--
--   标记长在记忆上（路一）：桶名/正文以【实】/【悬】/【空】开头，
--   附【证据】引文 + tag g:实|悬|空。无标记记忆视为不可靠（安全网）。
-- ============================================================

CREATE TABLE IF NOT EXISTS memory_topics (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  topic TEXT NOT NULL UNIQUE,             -- 归一化主题词，如"搬家计划"
  bucket_id TEXT,                         -- Ombre 桶 ID（hold 返回；未知时先 NULL，靠 breath_search 定位）
  grounding TEXT NOT NULL DEFAULT '实',   -- 上次写入的可信度 实/悬/空
  evidence TEXT,                          -- 证据引文
  importance REAL NOT NULL DEFAULT 0.5,   -- 0~1
  last_content TEXT,                      -- 上次写入的完整内容（含【实/悬/空】+【证据】），用于差分对比
  snapshot_hash TEXT,                     -- sha256(last_content)，零变化跳过的快速判定
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_memory_topics_topic ON memory_topics (topic);

-- RLS 由 2026-08-13-rls.sql 迁移统一启用
