-- ============================================================
-- memory_relations — 记忆关系边（缝合怪/Scarlett 思想的轻量版）
-- 在 Supabase SQL Editor 手动执行（不自动迁移）
--
-- 设计说明：
--   这是「边缘列表」，不是知识图谱——只有 source/target 两列 + 一个类型。
--   七类关系（触发/导致 分开给更细的因果语义，来自缝合怪图 1 + GPT 拆法）：
--     触发   A 是 B 的由头/契机（如"看到打雷"触发了回忆）
--     导致   A 直接导致了 B（如"设计猫猫"导致"加音乐记忆"）
--     贡献   A 促成了 B（不如"导致"强，是参与因子）
--     改善   A 改善了 B / B 是对 A 的修正
--     解释   A 解释了 B（为什么会有 B 的来龙去脉）
--     更新   B 更新/取代了 A（同一主题的演化）
--     同类   A 与 B 同类（同一原子事实的证据束 / 相关事件）
--   note = cc 注释：为什么建立这条关系（逐字诚实的依据，检索时带进上下文）。
--   检索时从命中话题做 1~2 hop 扩展，形成因果故事（见 server.js getAttentionMaterial）。
-- ============================================================

CREATE TABLE IF NOT EXISTS memory_relations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  source_topic TEXT NOT NULL,              -- 来源主题（memory_topics.topic 的字符串；V1 不建外键，防话题归并漂移）
  target_topic TEXT NOT NULL,              -- 目标主题
  rel_type TEXT NOT NULL
    CHECK (rel_type IN ('触发','导致','贡献','改善','解释','更新','同类')),
  note TEXT,                               -- cc 注释：这条关系为什么成立
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (source_topic, target_topic, rel_type)   -- 防重复边
);

CREATE INDEX IF NOT EXISTS idx_memory_relations_source ON memory_relations (source_topic);
CREATE INDEX IF NOT EXISTS idx_memory_relations_target ON memory_relations (target_topic);

-- 与其他表一致：关 RLS（默认开且无策略会 INSERT 被拒、SELECT 被静默过滤）
ALTER TABLE memory_relations DISABLE ROW LEVEL SECURITY;
