-- ============================================================
-- request_stats — 每次 chat 请求的真实 usage + Context Assembly 诊断
-- 在 Supabase SQL Editor 手动执行（不自动迁移）
--
-- 设计说明：
--  usage_raw 存 OpenRouter 返回的完整原始 usage（JSONB），常见字段单独拆列。
--  命中率 / 节省比例等派生指标不要固化成列——先确认 provider 语义，再从原始数据算。
-- ============================================================

CREATE TABLE IF NOT EXISTS request_stats (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id INTEGER NOT NULL,
  client TEXT NOT NULL,                -- 'angel' | 'legacy'
  model TEXT,
  stream BOOLEAN,
  tool_rounds INTEGER NOT NULL DEFAULT 1,   -- 一次 chat 请求包含的 OpenRouter 调用轮数
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- 原始 usage（完整保留，语义之后核对）
  usage_raw JSONB,

  -- 常见字段拆列（多轮工具请求取各轮之和）
  prompt_tokens INTEGER,
  completion_tokens INTEGER,
  total_tokens INTEGER,
  cached_tokens INTEGER,               -- OpenAI 风格 prompt_tokens_details.cached_tokens（命中读取，是 prompt_tokens 的子集）
  cache_write_tokens INTEGER,          -- OpenAI 风格 prompt_tokens_details.cache_write_tokens（写入缓存，等价 Anthropic cache_creation，是 prompt_tokens 的子集）
  cache_read_input_tokens INTEGER,     -- Anthropic 风格顶层字段
  cache_creation_input_tokens INTEGER, -- Anthropic 风格顶层字段
  reasoning_tokens INTEGER,            -- completion_tokens_details.reasoning_tokens

  -- Context Assembly 诊断（仅 angel 有值，legacy / memory-off 为 null）
  history_turns INTEGER,
  frozen_turns INTEGER,
  summary_present BOOLEAN,
  summary_from INTEGER,
  summary_to INTEGER,
  middle_raw_turns INTEGER,
  live_turns INTEGER,
  messages_sent INTEGER,
  estimated_tokens INTEGER,
  trimmed_turns INTEGER,
  frozen_prefix_hash TEXT,
  summary_hash TEXT,
  live_hash TEXT
);

CREATE INDEX IF NOT EXISTS idx_request_stats_created_at ON request_stats (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_request_stats_session ON request_stats (session_id);
CREATE INDEX IF NOT EXISTS idx_request_stats_client ON request_stats (client);

-- 关键：新建表默认会开 RLS 且无策略 → INSERT 被拒（42501）、SELECT 被静默过滤。
-- 其他表（sessions/messages 等）都是关 RLS 的，这里保持一致。
-- 若想保留 RLS，改为：CREATE POLICY "request_stats_all" ON request_stats FOR ALL USING (true) WITH CHECK (true);
ALTER TABLE request_stats DISABLE ROW LEVEL SECURITY;

-- 已按旧版建表（无 cache_write_tokens 列）的迁移：
-- ALTER TABLE request_stats ADD COLUMN IF NOT EXISTS cache_write_tokens INTEGER;
